FROM node:22-alpine

WORKDIR /app

COPY package.json yarn.lock ./

RUN yarn install

COPY . .

RUN yarn build

RUN yarn global add serve

RUN addgroup -S appgroup && adduser -S appuser -G appgroup

USER appuser

EXPOSE 80

CMD ["serve", "-s", "build", "-l", "80"]