
FROM node:22-alpine AS build


WORKDIR /app


COPY package.json yarn.lock ./


RUN yarn install 


COPY . .


RUN yarn build


FROM node:22-alpine

WORKDIR /app


RUN yarn global add serve

# Create non-root user
RUN addgroup -S appgroup && adduser -S appuser -G appgroup


USER appuser


COPY --from=build /app/build ./build

EXPOSE 80


CMD ["serve", "-s", "build", "-l", "80"]
