name: Terraform apply Pipeline

on:
  workflow_dispatch:

jobs:
  terraform_apply:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: configure aws credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{secrets.AWS_IAM_WRITE_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform setup
        uses: hashicorp/setup-terraform@v4


      - name: Terraform Init
        id: init
        run: terraform init -input=false
        working-directory: ./infra

     
      - name: Download plan artifact
        uses: actions/download-artifact@v4
        with:
             name: tfplan
             path: ./infra/

      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve tfplan
        working-directory: ./infra

      - name: Health check
        run: |
          sleep 30
          curl --fail https://tm.esproject.xyz/health

