name: Terraform Destroy Pipeline

on:
  workflow_dispatch:

jobs:
  terraform_destroy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: configure aws credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{secrets.AWS_WRITE_ROLE_ARN}}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform setup
        uses: hashicorp/setup-terraform@v4

      - name: Terraform Init
        id: init
        run: terraform init -input=false
        working-directory: ./infra

      
      - name: Terraform destroy
        id: destroy
        run: terraform destroy -auto-approve -no-color
        working-directory: ./infra


