name: Docker pipeline

on:
  workflow_dispatch:
  push:
      branches:
        - main
      paths:
        - 'app/**'
        - 'Dockerfile'

jobs:
  docker_build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      IMAGE_TAG: ${{ github.sha }}
      ECR_REGISTRY: ""

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: configure aws credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with: 
          role-to-assume: ${{secrets.AWS_WRITE_ROLE_ARN}}
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: Retrieve Ecr URL via SSM
        run : | 
         ECR_URL=$(aws ssm get-parameter --name "/ecs-project/ecr/repository_url" --query "Parameter.Value" --output text )
         echo "ECR_REGISTRY=$ECR_URL" >> $GITHUB_ENV
        
      - name: Build Docker image
        run: |
          docker build -t $ECR_REGISTRY:$IMAGE_TAG ./app

      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.ECR_REGISTRY }}:${{ env.IMAGE_TAG }}
          format: table
          severity: CRITICAL
          exit-code: 1
          ignore-unfixed: true

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Push Docker image
        run: |
          docker push $ECR_REGISTRY:$IMAGE_TAG

      
      - name: Render ECS task definition
        id: render-task
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
            task-definition-family: ${{ secrets.ECS_TASK_FAMILY }} 
            container-name: ${{ secrets.ECS_CONTAINER_NAME }}             
            image: ${{ env.ECR_REGISTRY }}:${{ env.IMAGE_TAG }}

      
      - name: Deploy ECS service
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
            task-definition: ${{ steps.render-task.outputs.task-definition }}
            service: ${{ secrets.ECS_SERVICE_NAME }}
            cluster: ${{ secrets.ECS_CLUSTER_NAME }}
            wait-for-service-stability: true