name: Docker pipeline

on:
  workflow_dispatch:
  push:
      branches:
        - main
      paths:
        - 'app/**'
        - 'Dockerfile'
        
jobs:
  docker_build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      ECR_REPOSITORY: ecs_pipeline
      IMAGE_TAG: ${{ github.sha }}
      ECR_REGISTRY: ""

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: configure aws credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with: 
          role-to-assume: ${{secrets.AWS_IAM_WRITE_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: Retrieve Ecr URL via SSM
        run : | 
         ECR_URL=$(aws ssm get-parameter --name "/ecs-project/ecr/repository_url" --query "Parameter.Value" --output text )
         echo "ECR_REGISTRY=$ECR_URL" >> $GITHUB_ENV
        
      - name: Build Docker image
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ./app

      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}
          format: table
          severity: CRITICAL
          exit-code: 1
          ignore-unfixed: true

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Push Docker image
        run: |
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG