name: Terraform Plan Pipeline

on:
  workflow_dispatch:
  pull_request:
      branches:
        - main
      paths:
        - 'infra/**'
        
    

jobs:
  terraform_plan:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: configure aws credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{secrets.AWS_READ_ROLE_ARN}}
          aws-region: eu-west-2


      - name: Terraform setup
        uses: hashicorp/setup-terraform@v4

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        working-directory: ./infra

      - name: Terraform Init
        id: init
        run: terraform init -input=false
        working-directory: ./infra

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
        working-directory: ./infra

      - name: Run Checkov action
        id: checkov
        uses: bridgecrewio/checkov-action@v12 
        with:
         directory: ./infra
         skip_check: CKV_AWS_158,CKV_AWS_136,CKV_AWS_152,CKV_AWS_91,CKV_AWS_130,CKV2_AWS_11,CKV_AWS_34

      - name: Terraform Plan
        id: plan
        run: terraform plan -out=tfplan -input=false
        working-directory: ./infra
      
      - name: Upload plan artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: ./infra/tfplan
      
      

